### ISSUE TITLE
Tracking: Set up unit and functional test CI for Linux

### ISSUE THREAD

**Issue by chrisd8088** [github/VFSForGit#18]
This tracking issue is intended as a roadmap of the steps required to implement the full functional test suite of VFSForGit in Azure DevOps CI for the Linux platform.

- Enable full Linux unit test CI on the `features/linuxprototype` branch:
  - [x] Enable the `PR - Linux - Build and Unit Test` pipeline with `MirrorProvider` build tasks on all PRs to branch (thanks, @jrbriggs!)
  - [x] Merge microsoft/vfsforGit#1128, then remove the `CPPFLAGS` environment variables from the `MirrorProvider` build tasks.
  - [x] Merge #21 into microsoft/vfsforGit#1125.
  - [x] Implement github/libprojfs#71 (#20) (#24) (#27) (#28)
  - [x] Merge microsoft/vfsforGit#1125, then enable the `VFSForGit` build tasks within the `PR - Linux - Build and Unit Test` pipeline.
  - [x] Implement github/libprojfs#72 (#23)
  - [x] Support case-sensitive file matching (#29) (microsoft/VFSForGit#1232) (microsoft/VFSForGit#1412) (microsoft/VFSForGit#1503) (microsoft/VFSForGit#1531)
- Resolve any outstanding problems running the functional test suite on Linux:
  - [x] Enable all relevant functional tests marked Mac-only or Windows-only. (#33)
  - [x] Ensure any necessary PRs are merged into `features/linuxprototype` (microsoft/VFSForGit#1432)
  - [x] Ensure any necessary PRs are merged into `master` (microsoft/VFSForGit#1411) (microsoft/VFSForGit#1412) (microsoft/VFSForGit#1413) (microsoft/VFSForGit#1448) (microsoft/VFSForGit#1529) (microsoft/VFSForGit#1535)
- Resolve custom Git installation and packaging:
  - [x] Rewrite "git build Linux installer" task to create `.deb` package within NuGet package and push to MyGet.
  - [x] Add Linux build task to "git - build installers" pipeline.
- Enable full Linux functional test CI on the `features/linuxprototype` branch:
  - [x] Either an Azure DevOps task group, or, if following the Mac model, a GitHub CI job instead.

Possible additional steps:
- Once functional test CI is successfully working on `features/linuxprototype`:
  - Refactor out all duplicate code between the Mac and Linux implementations, expanding the POSIX layer (e.g., introducing a `ProjFS.POSIX` set of classes as per the [`posix-projfs-virt-instance`](https://github.com/github/VFSForGit/tree/posix-projfs-virt-instance) branch.
  - Merge `features/linuxprototype` into  `master` and convert both CI jobs to run against `master`.
  - 🍾 or 🍨, as desired.

**Comment by chrisd8088** [comment]
Functional tests ran to completion on Linux in https://github.com/microsoft/VFSForGit/pull/1310 WIP branch.

**Comment by chrisd8088** [comment]
Automatic CI execution of the functional tests has been enabled for a while now on the `features/linuxprototype` branch.
